### ISSUE TITLE
Pod structure would be nice as an option

### ISSUE THREAD

**Issue by kentmw** [arikwex/quick-sip#1]
Rather than have scripts and styles be separate, I'd like to be able to define pod structures.

**Comment by arikwex** [comment]
I like the idea of configurable project structures.  This means that the public API should expose some configuration.  What sort of flavor are you looking for?
e.g.

var gulp = require('gulp');
var sip = require('quick-sip')(gulp);
sip.setRootJS('main.js');
sip.setRootSCSS('app.scss');

Thoughts?

**Comment by arikwex** [comment]
Also, I just examine your commit... Wouldn't you rather make that path object configurable?

**Comment by kentmw** [comment]
Yep, all those sound good. Just wanted to get the ball moving

**Comment by mandragorn** [comment]
Additionally:
sip.addJSPath('some/other/path/to/browserify')
sip.addSCSSPath('...')
sip.noSCSS() // Not sure if this is needed, but thinking about projects that do not compile their own scss.
