### ISSUE TITLE
I had to specify browserify.root in default overrides

### ISSUE THREAD

**Issue by kentmw** [arikwex/quick-sip#17]
I received this error:
[BROWSERIFY] @ 13:39:24 9/8/2015 
Error: Cannot find module '/other/dev/myproj/server/server-spa/undefined/app' from '/other/dev/myproj/server/server-spa'

that went away when I added the default: 

```
  browserify: {
    root: './app/app',
    ...
```

**Comment by kentmw** [comment]
same thing with styles

**Comment by mandragorn** [comment]
@kentmw  - please move this to the vecna project for quick-sip since we are no longer pushing vecna changes to this repo (Blake will be updating npm to list Vecna's repo instead).  Also Blake and Deena are actively working on fixing this.

**Comment by kentmw** [comment]
done
https://github.com/vecnatechnologies/quick-sip/issues/8
